"""baseline existing schema

Revision ID: 0001
Revises: 
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=80), nullable=False),
    sa.Column('details', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('beds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('bed_number', sa.Integer(), nullable=False),
    sa.Column('ward', sa.String(length=50), nullable=False),
    sa.Column('bed_type', sa.String(length=50), nullable=False),
    sa.Column('is_occupied', sa.Boolean(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_beds_bed_number'), ['bed_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_beds_is_occupied'), ['is_occupied'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('patients',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_code', sa.String(length=20), nullable=False),
    sa.Column('full_name', sa.String(length=120), nullable=False),
    sa.Column('date_of_birth', sa.String(length=20), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=False),
    sa.Column('blood_group', sa.String(length=5), nullable=False),
    sa.Column('height_cm', sa.Float(), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('emergency_contact', sa.String(length=30), nullable=True),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('photo_path', sa.String(length=255), nullable=False),
    sa.Column('face_encoding', sa.Text(), nullable=True),
    sa.Column('bed_number', sa.Integer(), nullable=True),
    sa.Column('admission_date', sa.DateTime(), nullable=False),
    sa.Column('discharge_date', sa.DateTime(), nullable=True),
    sa.Column('portal_pin', sa.String(length=12), nullable=True),
    sa.Column('portal_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['bed_number'], ['beds.bed_number'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patients_admission_date'), ['admission_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_bed_number'), ['bed_number'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_discharge_date'), ['discharge_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_patients_patient_code'), ['patient_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_patients_status'), ['status'], unique=False)

    op.create_table('medications',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('medicine_name', sa.String(length=120), nullable=False),
    sa.Column('dosage', sa.String(length=60), nullable=False),
    sa.Column('frequency', sa.String(length=60), nullable=False),
    sa.Column('scheduled_time', sa.String(length=60), nullable=False),
    sa.Column('start_date', sa.DateTime(), nullable=False),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medications_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medications_status'), ['status'], unique=False)

    op.create_table('robot_tasks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('assigned_by', sa.String(length=120), nullable=False),
    sa.Column('task_type', sa.String(length=50), nullable=False),
    sa.Column('instructions', sa.Text(), nullable=False),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('assigned_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_robot_tasks_assigned_at'), ['assigned_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_robot_tasks_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_robot_tasks_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_robot_tasks_status'), ['status'], unique=False)

    op.create_table('health_check_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('robot_task_id', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['robot_task_id'], ['robot_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('health_check_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_health_check_sessions_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_check_sessions_robot_task_id'), ['robot_task_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_health_check_sessions_started_at'), ['started_at'], unique=False)

    op.create_table('medication_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('medication_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('scheduled_time', sa.DateTime(), nullable=False),
    sa.Column('administered_time', sa.DateTime(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('dispensing_source', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['medication_id'], ['medications.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medication_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medication_logs_medication_id'), ['medication_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medication_logs_patient_id'), ['patient_id'], unique=False)

    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('alert_type', sa.String(length=60), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('acknowledged_at', sa.DateTime(), nullable=True),
    sa.Column('acknowledged_by', sa.String(length=120), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['health_check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_alerts_status'), ['status'], unique=False)

    op.create_table('emotion_records',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('emotion', sa.String(length=50), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['health_check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('emotion_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_emotion_records_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_records_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_emotion_records_session_id'), ['session_id'], unique=False)

    op.create_table('medical_summaries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=120), nullable=False),
    sa.Column('clinical_summary', sa.Text(), nullable=False),
    sa.Column('patient_summary', sa.Text(), nullable=True),
    sa.Column('temperature_c', sa.String(length=30), nullable=True),
    sa.Column('pulse_bpm', sa.String(length=30), nullable=True),
    sa.Column('spo2_percent', sa.String(length=30), nullable=True),
    sa.Column('ecg_note', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['health_check_sessions.id'], ),
    sa.ForeignKeyConstraint(['task_id'], ['robot_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('medical_summaries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_medical_summaries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_summaries_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_summaries_session_id'), ['session_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_medical_summaries_task_id'), ['task_id'], unique=False)

    op.create_table('patient_responses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['health_check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('patient_responses', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_patient_responses_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_patient_responses_session_id'), ['session_id'], unique=False)

    op.create_table('vital_readings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('temperature_c', sa.Float(), nullable=False),
    sa.Column('pulse_bpm', sa.Float(), nullable=False),
    sa.Column('spo2_percent', sa.Float(), nullable=False),
    sa.Column('ecg_value', sa.String(length=50), nullable=True),
    sa.Column('ecg_note', sa.String(length=255), nullable=True),
    sa.Column('recorded_at', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('quality_status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['health_check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_vital_readings_patient_id'), ['patient_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_recorded_at'), ['recorded_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_vital_readings_session_id'), ['session_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    raise RuntimeError("Downgrade would delete patient data; restore a backup instead.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vital_readings_session_id'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_recorded_at'))
        batch_op.drop_index(batch_op.f('ix_vital_readings_patient_id'))

    op.drop_table('vital_readings')
    with op.batch_alter_table('patient_responses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patient_responses_session_id'))
        batch_op.drop_index(batch_op.f('ix_patient_responses_patient_id'))

    op.drop_table('patient_responses')
    with op.batch_alter_table('medical_summaries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medical_summaries_task_id'))
        batch_op.drop_index(batch_op.f('ix_medical_summaries_session_id'))
        batch_op.drop_index(batch_op.f('ix_medical_summaries_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medical_summaries_created_at'))

    op.drop_table('medical_summaries')
    with op.batch_alter_table('emotion_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_emotion_records_session_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_records_patient_id'))
        batch_op.drop_index(batch_op.f('ix_emotion_records_detected_at'))

    op.drop_table('emotion_records')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_alerts_patient_id'))
        batch_op.drop_index(batch_op.f('ix_alerts_created_at'))

    op.drop_table('alerts')
    with op.batch_alter_table('medication_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medication_logs_patient_id'))
        batch_op.drop_index(batch_op.f('ix_medication_logs_medication_id'))

    op.drop_table('medication_logs')
    with op.batch_alter_table('health_check_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_health_check_sessions_started_at'))
        batch_op.drop_index(batch_op.f('ix_health_check_sessions_robot_task_id'))
        batch_op.drop_index(batch_op.f('ix_health_check_sessions_patient_id'))

    op.drop_table('health_check_sessions')
    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robot_tasks_status'))
        batch_op.drop_index(batch_op.f('ix_robot_tasks_priority'))
        batch_op.drop_index(batch_op.f('ix_robot_tasks_patient_id'))
        batch_op.drop_index(batch_op.f('ix_robot_tasks_assigned_at'))

    op.drop_table('robot_tasks')
    with op.batch_alter_table('medications', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_medications_status'))
        batch_op.drop_index(batch_op.f('ix_medications_patient_id'))

    op.drop_table('medications')
    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_patients_status'))
        batch_op.drop_index(batch_op.f('ix_patients_patient_code'))
        batch_op.drop_index(batch_op.f('ix_patients_full_name'))
        batch_op.drop_index(batch_op.f('ix_patients_discharge_date'))
        batch_op.drop_index(batch_op.f('ix_patients_bed_number'))
        batch_op.drop_index(batch_op.f('ix_patients_admission_date'))

    op.drop_table('patients')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('beds', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_beds_is_occupied'))
        batch_op.drop_index(batch_op.f('ix_beds_bed_number'))

    op.drop_table('beds')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
