"""quality alerts notes robot status

Revision ID: 0002
Revises: 0001
"""
from alembic import op
import sqlalchemy as sa


revision = '0002'
down_revision = '0001'
branch_labels = None
depends_on = None


def upgrade():
    bind = op.get_bind()
    existing_tables = set(sa.inspect(bind).get_table_names())
    missing = bind.execute(sa.text("SELECT COUNT(*) FROM patients WHERE portal_pin IS NOT NULL AND portal_pin_hash IS NULL")).scalar_one()
    if missing:
        raise RuntimeError("Run python -m database.backfill_portal_pin_hashes before upgrading: plaintext-only PIN rows exist.")
    if 'auth_attempts' not in existing_tables:
        op.create_table('auth_attempts',
        sa.Column('id', sa.Integer(), primary_key=True, autoincrement=True),
        sa.Column('scope', sa.String(length=20), nullable=False),
        sa.Column('identifier_hash', sa.String(length=64), nullable=False),
        sa.Column('ip_address', sa.String(length=50), nullable=False),
        sa.Column('failures', sa.Integer(), nullable=False),
        sa.Column('first_failure_at', sa.DateTime(), nullable=False),
        sa.Column('blocked_until', sa.DateTime(), nullable=True),
        sa.UniqueConstraint('scope', 'identifier_hash', 'ip_address', name='uq_auth_attempt_identity'))
    # ### commands auto generated by Alembic - please adjust! ###
    if 'robot_statuses' not in existing_tables:
        op.create_table('robot_statuses',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('robot_id', sa.String(length=80), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('current_task_id', sa.Integer(), nullable=True),
    sa.Column('battery_percent', sa.Float(), nullable=True),
    sa.Column('detail', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['current_task_id'], ['robot_tasks.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('robot_statuses', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_robot_statuses_last_seen_at'), ['last_seen_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_robot_statuses_robot_id'), ['robot_id'], unique=True)

    if 'clinical_notes' not in existing_tables:
        op.create_table('clinical_notes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('author_name', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('note_type', sa.String(length=40), nullable=False),
    sa.Column('related_session_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patients.id'], ),
    sa.ForeignKeyConstraint(['related_session_id'], ['health_check_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
        with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_clinical_notes_created_at'), ['created_at'], unique=False)
            batch_op.create_index(batch_op.f('ix_clinical_notes_patient_id'), ['patient_id'], unique=False)

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vital_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('metric', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('actual_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('threshold_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('previous_value', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('delta', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('resolved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('resolved_by', sa.String(length=120), nullable=True))
        batch_op.add_column(sa.Column('resolution_note', sa.Text(), nullable=True))
        batch_op.create_index(batch_op.f('ix_alerts_vital_id'), ['vital_id'], unique=False)
        batch_op.create_foreign_key('fk_alerts_vital_id', 'vital_readings', ['vital_id'], ['id'])

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('actor_role', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('entity_type', sa.String(length=60), nullable=True))
        batch_op.add_column(sa.Column('entity_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('source', sa.String(length=60), nullable=True))

    with op.batch_alter_table('patients', schema=None) as batch_op:
        batch_op.add_column(sa.Column('assigned_doctor_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_patients_assigned_doctor_id'), ['assigned_doctor_id'], unique=False)
        batch_op.create_foreign_key('fk_patients_assigned_doctor_id', 'users', ['assigned_doctor_id'], ['id'])

    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('robot_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('current_stage', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('stage_updated_at', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_robot_tasks_robot_id'), ['robot_id'], unique=False)

    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temperature_status', sa.String(length=30), nullable=False, server_default='measured'))
        batch_op.add_column(sa.Column('pulse_status', sa.String(length=30), nullable=False, server_default='measured'))
        batch_op.add_column(sa.Column('spo2_status', sa.String(length=30), nullable=False, server_default='measured'))
        batch_op.add_column(sa.Column('temperature_quality', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pulse_quality', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('spo2_quality', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('device_id', sa.String(length=80), nullable=True))
        batch_op.alter_column('temperature_c',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('pulse_bpm',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('spo2_percent',
               existing_type=sa.FLOAT(),
               nullable=True)

    # Preserve provenance from historical rows; do not infer missing samples.
    op.execute("UPDATE vital_readings SET temperature_status = 'simulated', pulse_status = 'simulated', spo2_status = 'simulated' WHERE quality_status = 'simulated'")
    op.execute("UPDATE vital_readings SET temperature_status = 'poor_signal', pulse_status = 'poor_signal', spo2_status = 'poor_signal' WHERE quality_status = 'noisy'")
    # Clear legacy plaintext PINs only after each row has a hash. Rows lacking
    # a hash require the explicit backfill script before this migration.
    op.execute("UPDATE patients SET portal_pin = NULL WHERE portal_pin IS NOT NULL")


def downgrade():
    raise RuntimeError("Downgrade would remove clinical data and is intentionally disabled. Restore a backup instead.")
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vital_readings', schema=None) as batch_op:
        batch_op.alter_column('spo2_percent',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('pulse_bpm',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('temperature_c',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.drop_column('device_id')
        batch_op.drop_column('spo2_quality')
        batch_op.drop_column('pulse_quality')
        batch_op.drop_column('temperature_quality')
        batch_op.drop_column('spo2_status')
        batch_op.drop_column('pulse_status')
        batch_op.drop_column('temperature_status')

    with op.batch_alter_table('robot_tasks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robot_tasks_robot_id'))
        batch_op.drop_column('stage_updated_at')
        batch_op.drop_column('current_stage')
        batch_op.drop_column('robot_id')

    with op.batch_alter_table('patients', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_patients_assigned_doctor_id'))
        batch_op.drop_column('assigned_doctor_id')

    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_column('source')
        batch_op.drop_column('entity_id')
        batch_op.drop_column('entity_type')
        batch_op.drop_column('actor_role')

    with op.batch_alter_table('alerts', schema=None) as batch_op:
        # WARNING: constraint name is None; this directive will fail as
        # rendered.  Add a name, or use a naming convention; see
        # https://alembic.sqlalchemy.org/en/latest/naming.html
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_alerts_vital_id'))
        batch_op.drop_column('resolution_note')
        batch_op.drop_column('resolved_by')
        batch_op.drop_column('resolved_at')
        batch_op.drop_column('source')
        batch_op.drop_column('delta')
        batch_op.drop_column('previous_value')
        batch_op.drop_column('threshold_value')
        batch_op.drop_column('actual_value')
        batch_op.drop_column('metric')
        batch_op.drop_column('vital_id')

    with op.batch_alter_table('clinical_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_clinical_notes_patient_id'))
        batch_op.drop_index(batch_op.f('ix_clinical_notes_created_at'))

    op.drop_table('clinical_notes')
    with op.batch_alter_table('robot_statuses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_robot_statuses_robot_id'))
        batch_op.drop_index(batch_op.f('ix_robot_statuses_last_seen_at'))

    op.drop_table('robot_statuses')
    # ### end Alembic commands ###
